version: "3"

services:
  client:
    stdin_open: true # to fix bug in create-react-app
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /app/node_modules
    - ./client:/app

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - ./server/.env

  nginx:
    depends_on:
      - client
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
    - "3000:80"
