version: '3'

services:
  client:
    stdin_open: true # to fix bug in create-react-app
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/incubo
    env_file:
      - .env

  nginx:
    depends_on:
      - client
      - api
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
